# Generated by Django 5.0 on 2024-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
